// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdZrGVjyKnUJgDHtJXEjzSex5PqEhO91c',
    appId: '1:184842207815:web:c8c16428215f9453a6a762',
    messagingSenderId: '184842207815',
    projectId: 'learn-app-4676e',
    authDomain: 'learn-app-4676e.firebaseapp.com',
    storageBucket: 'learn-app-4676e.appspot.com',
    measurementId: 'G-MG80V6BQ3F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeAbqR6hTUpK3pUpUT4l7KyGi8nL8KOUQ',
    appId: '1:184842207815:android:6fd757772e9ea30fa6a762',
    messagingSenderId: '184842207815',
    projectId: 'learn-app-4676e',
    storageBucket: 'learn-app-4676e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNmpnCLZ6YoGfcf3LmB3xpiuNYZGL6rKk',
    appId: '1:184842207815:ios:3599801fbc0933c1a6a762',
    messagingSenderId: '184842207815',
    projectId: 'learn-app-4676e',
    storageBucket: 'learn-app-4676e.appspot.com',
    iosBundleId: 'com.example.iLearn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNmpnCLZ6YoGfcf3LmB3xpiuNYZGL6rKk',
    appId: '1:184842207815:ios:eca249d459fdbbf5a6a762',
    messagingSenderId: '184842207815',
    projectId: 'learn-app-4676e',
    storageBucket: 'learn-app-4676e.appspot.com',
    iosBundleId: 'com.example.iLearn.RunnerTests',
  );
}
